AMT: v5.16-rc1
ANDROID: <= v5.19 # 1045a06724f3 ("remove CONFIG_ANDROID")
BAREUDP: v5.7-rc1
BITFIELD_KUNIT: v5.10-rc1
BITS_TEST: v5.9-rc1
BLK_CGROUP_IOLATENCY: v4.19-rc1
BLK_DEV_ZONED: v4.10-rc1
BOOTTIME_TRACING: v5.6-rc1
BPFILTER: v4.18-rc1
BPF_EVENTS: v4.1-rc1
BPF_JIT_ALWAYS_ON: v5.13-rc4
BPF_KPROBE_OVERRIDE: v4.16-rc1
BPF_LSM: v5.7-rc1
BPF_PRELOAD: v5.10-rc1
BPF_PRELOAD_UMD: v5.10-rc1
BPF_STREAM_PARSER: v4.14-rc1
BUILDTIME_MCOUNT_SORT: v5.17-rc1
CGROUP_BPF: v4.10-rc1
CMA_SIZE_MBYTES: <= v4.8-rc8
CMDLINE_KUNIT_TEST: v5.11-rc1
COMPAT_32BIT_TIME: v5.5-rc1
CPU_FREQ_GOV_SCHEDUTIL: v4.9-rc1
CPU_FREQ_STAT: v4.8-rc1
CRYPTO_BLAKE2B: v5.5-rc1
CRYPTO_DEV_VIRTIO: v4.10-rc1
CRYPTO_SM4: v4.17-rc1
CRYPTO_SM4_GENERIC: v5.19-rc1
CRYPTO_XXHASH: v5.3-rc1
DAMON: v5.15-rc1
DAMON_DBGFS: v5.15-rc1
DAMON_PADDR: v5.16-rc1
DAMON_VADDR: v5.15-rc1
DEBUG_INFO_BTF: v5.2-rc1
DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT: v5.12-rc2
DEBUG_PI_LIST: <= v5.1
DEBUG_PLIST: v5.2-rc1
DEFAULT_FQ_CODEL: v4.12-rc1
DEVICE_PRIVATE: v5.7-rc4
DMABUF_HEAPS: v5.6-rc1
DMABUF_HEAPS_SYSTEM: v5.6-rc1
DMA_CMA: <= v4.8-rc8
DMA_MAP_BENCHMARK: v5.11-rc1
DRIVER_PE_KUNIT_TEST: v5.13-rc1
DRM_DEBUG_SELFTEST: v4.18-rc1, <= v6.0
EDAC_ATOMIC_SCRUB: v4.2-rc1
EXT4_ENCRYPTION: <= v5.0
EXT4_KUNIT_TESTS: v5.5-rc1
F2FS_FS_ENCRYPTION: <= v5.0
FAIL_FUNCTION: v4.16-rc1
FAT_KUNIT_TEST: v5.15-rc1
FORCE_TASKS_RCU: v5.19-rc1
FORCE_TASKS_RUDE_RCU: v5.19-rc1
FORCE_TASKS_TRACE_RCU: v5.19-rc1
FTRACE_SORT_STARTUP_TEST: v5.17-rc1
FW_LOADER: v4.18-rc1
FW_LOADER_USER_HELPER: v4.18-rc1
FW_UPLOAD: v5.19-rc1
GENEVE: v4.3-rc1
GPIOLIB: v4.12-rc1
GPIO_CDEV: v5.10-rc1
GPIO_MOCKUP: v4.9-rc1
GPIO_SIM: v5.17-rc1
GUP_BENCHMARK: v4.15-rc1, <= v5.10
GUP_TEST: v5.11-rc1
HASH_KUNIT_TEST: v5.17-rc1
HIST_TRIGGERS: v4.7-rc1
IGC: v4.20-rc1
IMA: v5.11-rc1
IMA_ARCH_POLICY: v5.0-rc1
IMA_READ_POLICY: v5.11-rc1
IMA_WRITE_POLICY: v5.11-rc1
INFINIBAND_ADDR_TRANS: v4.17-rc1
INIT_ON_ALLOC_DEFAULT_ON: v5.14-rc1
INTEL_IDXD: v5.6-rc1
INTEL_RDT: v4.14-rc1, <= v4.20
INTEL_TH_STH: v4.4-rc1
ION: <= v5.10
ION_SYSTEM_HEAP: v4.12-rc1, <= v5.10
IPV6_FOU: v4.7-rc1
IPV6_FOU_TUNNEL: v4.7-rc1
IPV6_IOAM6_LWTUNNEL: v5.15
IPV6_SEG6_LWTUNNEL: v4.10-rc1
IRQ_POLL: v4.5-rc1
IR_IMON_DECODER: v4.17-rc1
KASAN_KUNIT_TEST: v5.10-rc1
KFENCE: v5.12-rc1
KFENCE_KUNIT_TEST: v5.12-rc1
KUNIT: v5.5-rc1
KUNIT_ALL_TESTS: v5.8-rc1
KUNIT_DEBUGFS: v5.7-rc1
KUNIT_EXAMPLE_TEST: v5.5-rc1
KUNIT_TEST: v5.5-rc1
LINEAR_RANGES_TEST: v5.8-rc1
LIST_KUNIT_TEST: v5.5-rc1
LIVEPATCH: v4.0-rc1
LWTUNNEL: v4.3-rc1
MEMCPY_KUNIT_TEST: v5.16-rc1
MEMORY_HOTPLUG_SPARSE: <= v5.15
MPLS: v4.1-rc1
MPLS_IPTUNNEL: v4.3-rc1
MPLS_ROUTING: v4.1-rc1
MPTCP: v5.6-rc1
MPTCP_IPV6: v5.6-rc1
MPTCP_KUNIT_TEST: v5.13-rc1
ND_BLK: <= v5.17
NETDEVSIM: v4.16-rc1
NETDEV_ADDR_LIST_TEST: v5.17-rc1
NET_ACT_BPF: v4.0-rc1
NET_ACT_CONNMARK: v4.0-rc1
NET_ACT_CT: v5.3-rc1
NET_ACT_CTINFO: v5.3-rc1
NET_ACT_GATE: v5.8-rc1
NET_ACT_IFE: v4.6-rc1
NET_ACT_MIRRED: v5.11-rc1
NET_ACT_MPLS: v5.3-rc1
NET_ACT_SAMPLE: v4.11-rc1
NET_ACT_SKBMOD: v4.9-rc1
NET_ACT_TUNNEL_KEY: v4.9-rc1
NET_CLS_FLOWER: v4.2-rc1
NET_EMATCH_IPT: v4.17-rc1
NET_IFE_SKBMARK: v4.6-rc1
NET_IFE_SKBPRIO: v4.6-rc1
NET_IFE_SKBTCINDEX: v4.9-rc1
NET_L3_MASTER_DEV: v4.4-rc1
NET_SCHED: v5.1-rc1
NET_SCH_CAKE: v4.19-rc1
NET_SCH_CBS: v4.15-rc1
NET_SCH_DEFAULT: v4.12-rc1
NET_SCH_ETF: v4.19-rc1
NET_SCH_ETS: v5.6-rc1
NET_SCH_INGRESS: v4.5-rc1
NET_SCH_SKBPRIO: v4.19-rc1
NET_SCH_TAPRIO: v4.20-rc1
NET_SELFTESTS: v5.13-rc1
NET_TC_SKB_EXT: v5.4-rc1
NET_VRF: v4.3-rc1
NFC: v5.12-rc1
NFC_NCI: v5.12-rc1
NFC_VIRTUAL_NCI: v5.12-rc1
NFT_CHAIN_NAT_IPV4: <= v5.0
NFT_CHAIN_NAT_IPV6: <= v5.0
NFT_COUNTER: <= v5.16-rc4
NFT_FLOW_OFFLOAD: v4.16-rc1
NFT_NAT: v5.1-rc1
NFT_OBJREF: v4.10-rc1
NFT_SYNPROXY: v5.9-rc1
NFT_TPROXY: v4.19-rc1
NF_CONNTRACK_LABELS: v4.19-rc1
NF_FLOW_TABLE: v4.16-rc1
NF_FLOW_TABLE_INET: v4.16-rc1
NF_FLOW_TABLE_IPV4: v4.16-rc1, <= v5.17-rc2
NF_FLOW_TABLE_IPV6: v4.16-rc1, <= v5.17-rc2
NF_NAT: v5.1-rc1
NF_TABLES_INET: v4.17-rc1
NF_TABLES_IPV4: v4.17-rc1
NF_TABLES_IPV6: v4.17-rc1
NF_TABLES_NETDEV: v4.17-rc1
NUMA: v5.6-rc1
NVMEM: v4.3-rc1
PM_QOS_KUNIT_TEST: v5.5-rc1
POSIX_TIMERS: v4.10-rc1
PREEMPTIRQ_DELAY_TEST: v5.6-rc1
PRIME_NUMBERS: v5.2-rc1
RANDOMIZE_KSTACK_OFFSET_DEFAULT: v5.14-rc1
RATIONAL_KUNIT_TEST: v5.14-rc1
RCU_PERF_TEST: <= v5.9
RCU_SCALE_TEST: v5.10-rc1
RC_CORE: v4.14-rc1
RDMA_RXE: v4.8-rc1
RDMA_SIW: v5.3-rc1
RESCTRL: v5.0-rc1
RESOURCE_KUNIT_TEST: v5.11-rc1
RTC_LIB_KUNIT_TEST: v5.15-rc1
SAMPLE_FTRACE_DIRECT: v5.5-rc1
SECURITYFS: v5.11-rc1
SECURITY_APPARMOR_KUNIT_TEST: v5.6-rc1
SECURITY_LANDLOCK: v5.13
SECURITY_LOADPIN_ENABLED: <= v4.19
SECURITY_LOADPIN_ENFORCE: v4.20-rc1
SECURITY_LOCKDOWN_LSM: v5.4-rc1
SLAB_FREELIST_HARDENED: v5.14-rc1
SLUB_KUNIT_TEST: v5.14-rc1
STM: v4.4-rc1
STM_DUMMY: v4.4-rc1
STM_SOURCE_CONSOLE: v4.4-rc1
STM_SOURCE_FTRACE: v4.6-rc1
STM_SOURCE_HEARTBEAT: v4.6-rc1
SYNC: <= v4.7
SYSCTL_KUNIT_TEST: v5.5-rc1
TASKS_RUDE_RCU: v5.8-rc1
TASKS_TRACE_RCU: v5.8-rc1
TEST_BITMAP: v4.6-rc1
TEST_BITOPS: v5.8-rc1
TEST_BLACKHOLE_DEV: v5.3-rc1
TEST_DIV64: v5.13-rc1
TEST_FPU: v5.9-rc1
TEST_FREE_PAGES: v5.10-rc1
TEST_HMM: v5.7-rc4
TEST_KMOD: v4.13-rc1
TEST_LIVEPATCH: v5.1-rc1
TEST_MEMINIT: v5.3-rc1
TEST_MIN_HEAP: v5.7-rc1
TEST_OVERFLOW: <= v5.17
TEST_PRINTF: v4.4-rc1
TEST_SCANF: v5.14-rc1
TEST_VMALLOC: v5.1-rc1
TIME_KUNIT_TEST: v5.14-rc1
TIME_NS: v5.6-rc1
TLS: v4.13-rc1
UBSAN_BOUNDS: v5.15-rc1
UDMABUF: v4.20-rc1
USB4: v5.6-rc1
USB4_KUNIT_TEST: v5.9-rc1
USERFAULTFD: v4.3-rc1
VALIDATE_FS_PARSER: v5.1-rc1
WATCH_QUEUE: v5.8-rc1
WW_MUTEX_SELFTEST: v4.11-rc1
X86_CPU_RESCTRL: v5.0-rc1
X86_MCELOG_LEGACY: v4.12-rc1
X86_RESCTRL: v5.0-rc2, <= v5.0-rc4
X86_SGX: v5.11-rc1
X86_VSMP: <= v5.2
XDP_SOCKETS: v4.18-rc1
XDP_SOCKETS_DIAG: v5.1-rc1
XFS_ONLINE_REPAIR: v4.18-rc1
XFS_ONLINE_SCRUB: v4.15-rc1
